# Generated by Django 4.0.6 on 2022-07-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='studio',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='zip',
            field=models.CharField(max_length=5),
        ),
    ]
