# Generated by Django 4.0.6 on 2022-07-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_class_studio_alter_student_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='city',
            field=models.CharField(max_length=150),
        ),
    ]
