# Generated by Django 4.0.6 on 2022-07-11 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_student_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='main_app.student'),
        ),
    ]
