# Generated by Django 4.0.6 on 2022-07-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_class_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.instructor'),
        ),
        migrations.AlterField(
            model_name='class',
            name='studio',
            field=models.IntegerField(max_length=1),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
