# Generated by Django 4.0.6 on 2022-07-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_class_instructor_alter_class_studio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ManyToManyField(related_name='classes', to='main_app.instructor'),
        ),
    ]
