# Generated by Django 4.0.6 on 2022-07-11 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_class_studio_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ManyToManyField(related_name='classes', to='main_app.instructor'),
        ),
    ]
