# Generated by Django 4.0.6 on 2022-07-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_remove_class_instructor_instructor_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='classes',
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ManyToManyField(related_name='classes', to='main_app.instructor'),
        ),
    ]
