# Generated by Django 4.0.6 on 2022-07-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_instructor_classes_class_instructor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='instructor',
            new_name='instructors',
        ),
    ]
