# Generated by Django 4.0.6 on 2022-07-13 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_class_day_of_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='instructor',
        ),
    ]
